use std::{
    env, fs, io,
    path::{Path, PathBuf},
    process,
};

const RATATUI_VERSION: &str = "0.30.1";
const CROSSTERM_VERSION: &str = "0.29.0";
const COLOR_EYRE_VERSION: &str = "0.6.5";
const TOKIO_VERSION: &str = "1";

fn main() {
    if let Err(error) = run(env::args().skip(1).collect()) {
        eprintln!("error: {error}");
        process::exit(1);
    }
}

fn run(args: Vec<String>) -> Result<(), String> {
    match args.as_slice() {
        [] => Err(usage()),
        [command] if command == "--help" || command == "-h" => {
            println!("{}", usage());
            Ok(())
        }
        [command, project_name] if command == "init" => init(project_name),
        [command, ..] if command == "init" => Err(
            "rustui init currently accepts only a project name; options are reserved for later"
                .to_string(),
        ),
        [command, ..] => Err(format!("unknown command `{command}`\n\n{}", usage())),
    }
}

fn usage() -> String {
    "usage:\n  rustui init <project_name>\n\nexample:\n  rustui init my-tui".to_string()
}

fn init(project_name: &str) -> Result<(), String> {
    let target = PathBuf::from(project_name);
    let package_name = package_name_for(&target)?;

    ensure_target_is_writable(&target)
        .map_err(|error| format!("cannot initialize `{}`: {error}", target.to_string_lossy()))?;

    let files = project_files(&package_name);
    for (relative_path, contents) in files {
        write_file(&target.join(relative_path), contents).map_err(|error| {
            format!(
                "failed to write `{}`: {error}",
                target.join(relative_path).to_string_lossy()
            )
        })?;
    }

    println!("created `{}`", target.to_string_lossy());
    println!("next:");
    println!("  cd {}", target.to_string_lossy());
    println!("  cargo run");

    Ok(())
}

fn package_name_for(target: &Path) -> Result<String, String> {
    let Some(name) = target.file_name().and_then(|name| name.to_str()) else {
        return Err("project name cannot be empty".to_string());
    };

    if !is_valid_package_name(name) {
        return Err(
            "project name must start with an ASCII letter and contain only letters, numbers, `_`, or `-`"
                .to_string(),
        );
    }

    Ok(name.to_string())
}

fn is_valid_package_name(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };

    first.is_ascii_alphabetic()
        && chars.all(|character| {
            character.is_ascii_alphanumeric() || character == '_' || character == '-'
        })
}

fn ensure_target_is_writable(target: &Path) -> io::Result<()> {
    if target.exists() {
        if target.read_dir()?.next().is_some() {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                "target directory already exists and is not empty",
            ));
        }
    } else {
        fs::create_dir_all(target)?;
    }

    fs::create_dir_all(target.join("src/tui"))?;
    Ok(())
}

fn write_file(path: &Path, contents: String) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(path, contents)
}

fn project_files(package_name: &str) -> Vec<(&'static str, String)> {
    vec![
        ("Cargo.toml", cargo_toml(package_name)),
        (".gitignore", gitignore()),
        ("README.md", readme(package_name)),
        ("src/main.rs", MAIN_RS.to_string()),
        ("src/app.rs", APP_RS.to_string()),
        ("src/tui/mod.rs", TUI_MOD_RS.to_string()),
        ("src/tui/command.rs", COMMAND_RS.to_string()),
        ("src/tui/keymap.rs", KEYMAP_RS.to_string()),
        ("src/tui/menu.rs", MENU_RS.to_string()),
        ("src/tui/style.rs", STYLE_RS.to_string()),
        ("src/tui/theme.rs", THEME_RS.to_string()),
    ]
}

fn cargo_toml(package_name: &str) -> String {
    format!(
        r#"[package]
name = "{package_name}"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "{COLOR_EYRE_VERSION}"
crossterm = "{CROSSTERM_VERSION}"
ratatui = "{RATATUI_VERSION}"
tokio = {{ version = "{TOKIO_VERSION}", features = ["macros", "rt-multi-thread", "sync", "time"] }}
"#
    )
}

fn gitignore() -> String {
    "/target\n".to_string()
}

fn readme(package_name: &str) -> String {
    format!(
        r#"# {package_name}

Generated by `rustui`.

## Interface Policy

- Quit is command-mode only: `:q`, `:quit`, `:exit`, or `:q!`.
- `Esc` cancels transient UI state. It never quits.
- `q` is available for local behavior, but it is not a global quit key.
- `Ctrl-C` is not bound to quit by default.
- `:` opens command mode from any pane.
- `?` opens help.
- `Tab` and `Shift-Tab` move focus.

The scaffold is intentionally editable. Start with `src/app.rs` for local
behavior, `src/tui/keymap.rs` for key policy, and `src/tui/theme.rs` for color
themes. `src/tui/style.rs` holds design tokens, selectors, and the style-rule
DSL for per-element styling. Tokio is part of the scaffold so blocking work can
be moved into background tasks without freezing the TUI scene.

## Non-Blocking Work

The TUI runtime is async. Use `tokio::spawn` for long-running work and send
results back through the app-owned task channel. `App::poll_tasks()` is called
from the render loop and is the standard place to fold task results back into
scene state.
"#
    )
}

const MAIN_RS: &str = r#"mod app;
mod tui;

use color_eyre::Result;

#[tokio::main]
async fn main() -> Result<()> {
    color_eyre::install()?;
    tui::run(app::App::default()).await
}
"#;

const TUI_MOD_RS: &str = r#"pub mod command;
pub mod keymap;
pub mod menu;
pub mod style;
pub mod theme;

use std::{io::stdout, time::Duration};

use color_eyre::Result;
use crossterm::{
    event::{self, DisableMouseCapture, EnableMouseCapture, Event, KeyEventKind},
    execute,
};
use ratatui::DefaultTerminal;
use tokio::{sync::mpsc, time};

use crate::app::App;

pub async fn run(mut app: App) -> Result<()> {
    let mut terminal = ratatui::init();
    execute!(stdout(), EnableMouseCapture)?;

    let result = run_app(&mut terminal, &mut app).await;

    let disable_result = execute!(stdout(), DisableMouseCapture);
    ratatui::restore();
    disable_result?;
    result
}

async fn run_app(terminal: &mut DefaultTerminal, app: &mut App) -> Result<()> {
    let mut events = spawn_event_reader();
    let mut tick = time::interval(Duration::from_millis(50));

    while !app.should_quit() {
        app.poll_tasks();
        terminal.draw(|frame| app.render(frame))?;

        tokio::select! {
            maybe_event = events.recv() => {
                match maybe_event {
                    Some(Event::Key(key)) if key.kind == KeyEventKind::Press => {
                        app.handle_key_event(key);
                    }
                    Some(Event::Mouse(mouse)) => app.handle_mouse_event(mouse),
                    Some(_) => {}
                    None => break,
                }
            }
            _ = tick.tick() => {}
        }
    }

    Ok(())
}

fn spawn_event_reader() -> mpsc::UnboundedReceiver<Event> {
    let (sender, receiver) = mpsc::unbounded_channel();
    std::thread::spawn(move || {
        loop {
            match event::read() {
                Ok(event) => {
                    if sender.send(event).is_err() {
                        break;
                    }
                }
                Err(_) => break,
            }
        }
    });
    receiver
}
"#;

const COMMAND_RS: &str = r#"#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Command {
    Quit { force: bool },
    Help,
    Theme(ThemeCommand),
    Unknown(String),
    Empty,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThemeCommand {
    Neutral,
    Safe,
    Danger,
}

pub fn parse(input: &str) -> Command {
    let trimmed = input.trim();
    if trimmed.is_empty() || trimmed == ":" {
        return Command::Empty;
    }

    if trimmed == "\\q" {
        return Command::Quit { force: false };
    }

    let Some(command) = trimmed.strip_prefix(':') else {
        return Command::Unknown(trimmed.to_string());
    };

    let mut parts = command.split_whitespace();
    let Some(name) = parts.next() else {
        return Command::Empty;
    };

    match name {
        "q" | "quit" | "exit" => Command::Quit { force: false },
        "q!" | "quit!" | "exit!" => Command::Quit { force: true },
        "help" | "?" => Command::Help,
        "theme" => match parts.next() {
            Some("neutral") | None => Command::Theme(ThemeCommand::Neutral),
            Some("safe") | Some("green") => Command::Theme(ThemeCommand::Safe),
            Some("danger") | Some("red") | Some("unsafe") => Command::Theme(ThemeCommand::Danger),
            Some(value) => Command::Unknown(format!("unknown theme `{value}`")),
        },
        _ => Command::Unknown(name.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::{parse, Command, ThemeCommand};

    #[test]
    fn parses_quit_aliases() {
        assert_eq!(parse(":q"), Command::Quit { force: false });
        assert_eq!(parse(":quit!"), Command::Quit { force: true });
        assert_eq!(parse("\\q"), Command::Quit { force: false });
    }

    #[test]
    fn parses_theme_aliases() {
        assert_eq!(parse(":theme safe"), Command::Theme(ThemeCommand::Safe));
        assert_eq!(
            parse(":theme unsafe"),
            Command::Theme(ThemeCommand::Danger)
        );
    }
}
"#;

const KEYMAP_RS: &str = r#"use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Intent {
    EnterCommandMode,
    Cancel,
    Help,
    NextPane,
    PreviousPane,
    Activate,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Search,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Key {
    Char(char),
    Esc,
    Enter,
    Tab,
    BackTab,
    Up,
    Down,
    Left,
    Right,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeyPattern {
    pub key: Key,
    pub modifiers: KeyModifiers,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeyBinding {
    pub pattern: KeyPattern,
    pub intent: Intent,
    pub label: &'static str,
    pub description: &'static str,
}

#[derive(Debug, Clone)]
pub struct Keymap {
    bindings: Vec<KeyBinding>,
}

impl Default for Keymap {
    fn default() -> Self {
        Self::common()
    }
}

impl Keymap {
    pub fn common() -> Self {
        let none = KeyModifiers::NONE;
        Self {
            bindings: vec![
                binding(Key::Char(':'), none, Intent::EnterCommandMode, ":", "command mode"),
                binding(Key::Esc, none, Intent::Cancel, "Esc", "cancel transient UI"),
                binding(Key::Char('?'), none, Intent::Help, "?", "help"),
                binding(Key::Tab, none, Intent::NextPane, "Tab", "next pane"),
                binding(Key::BackTab, none, Intent::PreviousPane, "Shift-Tab", "previous pane"),
                binding(Key::Enter, none, Intent::Activate, "Enter", "activate"),
                binding(Key::Up, none, Intent::MoveUp, "Up", "move up"),
                binding(Key::Down, none, Intent::MoveDown, "Down", "move down"),
                binding(Key::Left, none, Intent::MoveLeft, "Left", "move left"),
                binding(Key::Right, none, Intent::MoveRight, "Right", "move right"),
                binding(Key::Char('/'), none, Intent::Search, "/", "search"),
            ],
        }
    }

    #[allow(dead_code)]
    pub fn with_binding(mut self, binding: KeyBinding) -> Self {
        self.bindings.retain(|existing| existing.pattern != binding.pattern);
        self.bindings.push(binding);
        self
    }

    #[allow(dead_code)]
    pub fn without_key(mut self, pattern: KeyPattern) -> Self {
        self.bindings.retain(|existing| existing.pattern != pattern);
        self
    }

    pub fn intent_for(&self, key: KeyEvent) -> Option<Intent> {
        self.bindings
            .iter()
            .find(|binding| binding.pattern.matches(key))
            .map(|binding| binding.intent)
    }

    pub fn bindings(&self) -> &[KeyBinding] {
        &self.bindings
    }
}

pub fn binding(
    key: Key,
    modifiers: KeyModifiers,
    intent: Intent,
    label: &'static str,
    description: &'static str,
) -> KeyBinding {
    KeyBinding {
        pattern: KeyPattern { key, modifiers },
        intent,
        label,
        description,
    }
}

impl KeyPattern {
    pub fn matches(self, event: KeyEvent) -> bool {
        key_matches(self.key, event.code) && normalized_modifiers(event.modifiers) == self.modifiers
    }
}

fn key_matches(expected: Key, actual: KeyCode) -> bool {
    match (expected, actual) {
        (Key::Char(expected), KeyCode::Char(actual)) => expected == actual,
        (Key::Esc, KeyCode::Esc) => true,
        (Key::Enter, KeyCode::Enter) => true,
        (Key::Tab, KeyCode::Tab) => true,
        (Key::BackTab, KeyCode::BackTab) => true,
        (Key::Up, KeyCode::Up) => true,
        (Key::Down, KeyCode::Down) => true,
        (Key::Left, KeyCode::Left) => true,
        (Key::Right, KeyCode::Right) => true,
        _ => false,
    }
}

fn normalized_modifiers(mut modifiers: KeyModifiers) -> KeyModifiers {
    modifiers.remove(KeyModifiers::SHIFT);
    modifiers
}
"#;

const STYLE_RS: &str = r#"#![allow(dead_code)]

use ratatui::style::{Color, Modifier, Style};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorToken {
    Surface0,
    Surface1,
    Surface2,
    Border,
    Text,
    Muted,
    Accent,
    AccentLow,
    Success,
    Warning,
    Danger,
    Selection,
}

#[derive(Debug, Clone, Copy)]
pub struct Palette {
    pub surface0: Color,
    pub surface1: Color,
    pub surface2: Color,
    pub border: Color,
    pub text: Color,
    pub muted: Color,
    pub accent: Color,
    pub accent_low: Color,
    pub success: Color,
    pub warning: Color,
    pub danger: Color,
    pub selection: Color,
}

impl Palette {
    pub fn color(self, token: ColorToken) -> Color {
        match token {
            ColorToken::Surface0 => self.surface0,
            ColorToken::Surface1 => self.surface1,
            ColorToken::Surface2 => self.surface2,
            ColorToken::Border => self.border,
            ColorToken::Text => self.text,
            ColorToken::Muted => self.muted,
            ColorToken::Accent => self.accent,
            ColorToken::AccentLow => self.accent_low,
            ColorToken::Success => self.success,
            ColorToken::Warning => self.warning,
            ColorToken::Danger => self.danger,
            ColorToken::Selection => self.selection,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    AppBackground,
    Header,
    HeaderBrand,
    HeaderMode,
    Panel,
    PanelFocused,
    PanelTitle,
    Text,
    TextMuted,
    ListItem,
    ListItemSelected,
    Command,
    CommandFocused,
    PromptPrefix,
    PromptInput,
    Footer,
    FooterKey,
    HelpOverlay,
    HelpTitle,
    Status,
    StatusSuccess,
    StatusWarning,
    StatusDanger,
    Button,
    ButtonPrimary,
    ButtonDanger,
    ButtonFocused,
    Input,
    InputFocused,
    Badge,
    BadgeSuccess,
    BadgeWarning,
    BadgeDanger,
    TableHeader,
    TableCell,
    TableCellSelected,
}

impl Role {
    pub fn selector(self) -> &'static str {
        match self {
            Role::AppBackground => "app.background",
            Role::Header => "header",
            Role::HeaderBrand => "header.brand",
            Role::HeaderMode => "header.mode",
            Role::Panel => "panel",
            Role::PanelFocused => "panel.focused",
            Role::PanelTitle => "panel.title",
            Role::Text => "text",
            Role::TextMuted => "text.muted",
            Role::ListItem => "list.item",
            Role::ListItemSelected => "list.item.selected",
            Role::Command => "command",
            Role::CommandFocused => "command.focused",
            Role::PromptPrefix => "prompt.prefix",
            Role::PromptInput => "prompt.input",
            Role::Footer => "footer",
            Role::FooterKey => "footer.key",
            Role::HelpOverlay => "help.overlay",
            Role::HelpTitle => "help.title",
            Role::Status => "status",
            Role::StatusSuccess => "status.success",
            Role::StatusWarning => "status.warning",
            Role::StatusDanger => "status.danger",
            Role::Button => "button",
            Role::ButtonPrimary => "button.primary",
            Role::ButtonDanger => "button.danger",
            Role::ButtonFocused => "button.focused",
            Role::Input => "input",
            Role::InputFocused => "input.focused",
            Role::Badge => "badge",
            Role::BadgeSuccess => "badge.success",
            Role::BadgeWarning => "badge.warning",
            Role::BadgeDanger => "badge.danger",
            Role::TableHeader => "table.header",
            Role::TableCell => "table.cell",
            Role::TableCellSelected => "table.cell.selected",
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Rule {
    pub selector: &'static str,
    pub style: Style,
}

#[derive(Debug, Clone)]
pub struct Design {
    pub palette: Palette,
    rules: Vec<Rule>,
}

impl Design {
    pub fn new(palette: Palette) -> Self {
        Self {
            palette,
            rules: Vec::new(),
        }
    }

    pub fn role(self, role: Role, style: StyleBuilder) -> Self {
        self.selector(role.selector(), style)
    }

    pub fn selector(mut self, selector: &'static str, style: StyleBuilder) -> Self {
        self.rules.retain(|rule| rule.selector != selector);
        self.rules.push(Rule {
            selector,
            style: style.build(),
        });
        self
    }

    pub fn style(&self, selector: &str) -> Style {
        self.rules
            .iter()
            .rev()
            .find(|rule| rule.selector == selector)
            .map(|rule| rule.style)
            .unwrap_or_else(Style::default)
    }

    pub fn role_style(&self, role: Role) -> Style {
        self.style(role.selector())
    }

    pub fn color(&self, token: ColorToken) -> Color {
        self.palette.color(token)
    }
}

#[derive(Debug, Clone, Copy)]
pub struct StyleBuilder {
    style: Style,
}

pub fn style() -> StyleBuilder {
    StyleBuilder {
        style: Style::default(),
    }
}

impl StyleBuilder {
    pub fn fg(mut self, color: Color) -> Self {
        self.style = self.style.fg(color);
        self
    }

    pub fn bg(mut self, color: Color) -> Self {
        self.style = self.style.bg(color);
        self
    }

    pub fn bold(mut self) -> Self {
        self.style = self.style.add_modifier(Modifier::BOLD);
        self
    }

    pub fn dim(mut self) -> Self {
        self.style = self.style.add_modifier(Modifier::DIM);
        self
    }

    pub fn italic(mut self) -> Self {
        self.style = self.style.add_modifier(Modifier::ITALIC);
        self
    }

    pub fn underlined(mut self) -> Self {
        self.style = self.style.add_modifier(Modifier::UNDERLINED);
        self
    }

    pub fn reversed(mut self) -> Self {
        self.style = self.style.add_modifier(Modifier::REVERSED);
        self
    }

    pub fn build(self) -> Style {
        self.style
    }
}
"#;

const THEME_RS: &str = r#"#![allow(dead_code)]

use ratatui::style::{Color, Style};

use super::style::{style, ColorToken, Design, Palette, Role};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThemeKind {
    Neutral,
    Safe,
    Danger,
}

#[derive(Debug, Clone)]
pub struct Theme {
    pub name: &'static str,
    pub background: Color,
    pub panel: Color,
    pub border: Color,
    pub text: Color,
    pub muted: Color,
    pub accent: Color,
    pub accent_dark: Color,
    pub success: Color,
    pub warning: Color,
    pub danger: Color,
    pub design: Design,
}

impl Theme {
    pub fn style(&self, role: Role) -> Style {
        self.design.role_style(role)
    }

    pub fn selector(&self, selector: &str) -> Style {
        self.design.style(selector)
    }

    pub fn color(&self, token: ColorToken) -> Color {
        self.design.color(token)
    }

    pub fn palette(&self) -> Palette {
        self.design.palette
    }
}

impl ThemeKind {
    pub fn theme(self) -> Theme {
        let (name, palette) = match self {
            Self::Neutral => (
                "neutral",
                Palette {
                    surface0: Color::Rgb(14, 17, 22),
                    surface1: Color::Rgb(23, 28, 36),
                    surface2: Color::Rgb(33, 40, 52),
                    border: Color::Rgb(85, 95, 109),
                    text: Color::Rgb(232, 236, 241),
                    muted: Color::Rgb(151, 161, 175),
                    accent: Color::Rgb(89, 165, 216),
                    accent_low: Color::Rgb(34, 80, 111),
                    success: Color::Rgb(81, 178, 118),
                    warning: Color::Rgb(226, 173, 83),
                    danger: Color::Rgb(222, 96, 92),
                    selection: Color::Rgb(38, 72, 96),
                },
            ),
            Self::Safe => (
                "safe",
                Palette {
                    surface0: Color::Rgb(11, 20, 16),
                    surface1: Color::Rgb(20, 35, 27),
                    surface2: Color::Rgb(28, 48, 36),
                    border: Color::Rgb(70, 132, 98),
                    text: Color::Rgb(232, 241, 235),
                    muted: Color::Rgb(148, 171, 156),
                    accent: Color::Rgb(75, 190, 121),
                    accent_low: Color::Rgb(28, 92, 56),
                    success: Color::Rgb(75, 190, 121),
                    warning: Color::Rgb(226, 173, 83),
                    danger: Color::Rgb(222, 96, 92),
                    selection: Color::Rgb(31, 83, 54),
                },
            ),
            Self::Danger => (
                "danger",
                Palette {
                    surface0: Color::Rgb(24, 13, 13),
                    surface1: Color::Rgb(39, 22, 22),
                    surface2: Color::Rgb(55, 31, 31),
                    border: Color::Rgb(143, 76, 72),
                    text: Color::Rgb(246, 232, 230),
                    muted: Color::Rgb(182, 145, 140),
                    accent: Color::Rgb(228, 93, 86),
                    accent_low: Color::Rgb(111, 36, 34),
                    success: Color::Rgb(81, 178, 118),
                    warning: Color::Rgb(226, 173, 83),
                    danger: Color::Rgb(228, 93, 86),
                    selection: Color::Rgb(96, 39, 37),
                },
            ),
        };

        Theme {
            name,
            background: palette.surface0,
            panel: palette.surface1,
            border: palette.border,
            text: palette.text,
            muted: palette.muted,
            accent: palette.accent,
            accent_dark: palette.accent_low,
            success: palette.success,
            warning: palette.warning,
            danger: palette.danger,
            design: base_design(palette),
        }
    }
}

fn base_design(palette: Palette) -> Design {
    Design::new(palette)
        .role(
            Role::AppBackground,
            style().fg(palette.text).bg(palette.surface0),
        )
        .role(Role::Header, style().fg(palette.text).bg(palette.surface1))
        .role(
            Role::HeaderBrand,
            style().fg(palette.surface0).bg(palette.accent).bold(),
        )
        .role(
            Role::HeaderMode,
            style().fg(palette.text).bg(palette.accent_low).bold(),
        )
        .role(Role::Panel, style().fg(palette.text).bg(palette.surface1))
        .role(
            Role::PanelFocused,
            style().fg(palette.accent).bg(palette.surface1),
        )
        .role(Role::PanelTitle, style().fg(palette.accent).bold())
        .role(Role::Text, style().fg(palette.text).bg(palette.surface1))
        .role(Role::TextMuted, style().fg(palette.muted).bg(palette.surface1))
        .role(Role::ListItem, style().fg(palette.text).bg(palette.surface1))
        .role(
            Role::ListItemSelected,
            style().fg(palette.text).bg(palette.selection).bold(),
        )
        .role(Role::Command, style().fg(palette.text).bg(palette.surface1))
        .role(
            Role::CommandFocused,
            style().fg(palette.accent).bg(palette.surface1),
        )
        .role(Role::PromptPrefix, style().fg(palette.accent).bold())
        .role(Role::PromptInput, style().fg(palette.text))
        .role(Role::Footer, style().fg(palette.text).bg(palette.surface1))
        .role(Role::FooterKey, style().fg(palette.accent).bold())
        .role(Role::HelpOverlay, style().fg(palette.text).bg(palette.surface2))
        .role(Role::HelpTitle, style().fg(palette.accent).bold())
        .role(Role::Status, style().fg(palette.muted))
        .role(Role::StatusSuccess, style().fg(palette.success).bold())
        .role(Role::StatusWarning, style().fg(palette.warning).bold())
        .role(Role::StatusDanger, style().fg(palette.danger).bold())
        .role(Role::Button, style().fg(palette.text).bg(palette.surface2))
        .role(
            Role::ButtonPrimary,
            style().fg(palette.surface0).bg(palette.accent).bold(),
        )
        .role(
            Role::ButtonDanger,
            style().fg(palette.surface0).bg(palette.danger).bold(),
        )
        .role(Role::ButtonFocused, style().fg(palette.accent).underlined())
        .role(Role::Input, style().fg(palette.text).bg(palette.surface2))
        .role(
            Role::InputFocused,
            style().fg(palette.text).bg(palette.surface2).underlined(),
        )
        .role(Role::Badge, style().fg(palette.surface0).bg(palette.accent_low))
        .role(
            Role::BadgeSuccess,
            style().fg(palette.surface0).bg(palette.success).bold(),
        )
        .role(
            Role::BadgeWarning,
            style().fg(palette.surface0).bg(palette.warning).bold(),
        )
        .role(
            Role::BadgeDanger,
            style().fg(palette.surface0).bg(palette.danger).bold(),
        )
        .role(
            Role::TableHeader,
            style().fg(palette.surface0).bg(palette.accent).bold(),
        )
        .role(Role::TableCell, style().fg(palette.text).bg(palette.surface1))
        .role(
            Role::TableCellSelected,
            style().fg(palette.text).bg(palette.selection),
        )
        .selector("counter.value", style().fg(palette.accent).bold())
        .selector(
            "button.increment",
            style().fg(palette.surface0).bg(palette.success).bold(),
        )
        .selector(
            "button.decrement",
            style().fg(palette.surface0).bg(palette.warning).bold(),
        )
}
"#;

const MENU_RS: &str = r#"use ratatui::{
    style::Modifier,
    text::{Line, Span},
};

use super::{
    keymap::Keymap,
    style::Role,
    theme::{Theme, ThemeKind},
};

pub fn footer(keymap: &Keymap, theme: &Theme) -> Line<'static> {
    let mut spans = Vec::new();
    for binding in keymap.bindings().iter().take(6) {
        spans.push(Span::styled(
            binding.label,
            theme.style(Role::FooterKey)
                .add_modifier(Modifier::BOLD),
        ));
        spans.push(Span::raw(format!(" {}  ", binding.description)));
    }
    spans.push(Span::styled(
        ":q",
        theme.style(Role::FooterKey)
            .add_modifier(Modifier::BOLD),
    ));
    spans.push(Span::raw(" quit"));
    Line::from(spans)
}

pub fn help_lines(keymap: &Keymap, theme_kind: ThemeKind) -> Vec<Line<'static>> {
    let mut lines = vec![
        Line::from("Common Interface"),
        Line::from(""),
        Line::from("Quit is command-mode only: :q, :quit, :exit, :q!"),
        Line::from("Esc cancels transient state; it never quits."),
        Line::from(""),
        Line::from("Keys"),
    ];

    for binding in keymap.bindings() {
        lines.push(Line::from(format!(
            "  {:<10} {}",
            binding.label, binding.description
        )));
    }

    lines.extend([
        Line::from(""),
        Line::from("Commands"),
        Line::from("  :help              open help"),
        Line::from("  :theme neutral     neutral theme"),
        Line::from("  :theme safe        green safe theme"),
        Line::from("  :theme danger      red danger theme"),
        Line::from("  :q, :quit, :exit   quit"),
        Line::from("  :q!                force quit"),
        Line::from(""),
        Line::from(format!("Current theme: {:?}", theme_kind)),
    ]);

    lines
}
"#;

const APP_RS: &str = r#"use crossterm::event::{KeyCode, KeyEvent, KeyModifiers, MouseEvent, MouseEventKind};
use ratatui::{
    Frame,
    layout::{Constraint, Direction, Layout, Rect},
    style::{Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Clear, List, ListItem, ListState, Paragraph, Wrap},
};
use tokio::{
    sync::mpsc,
    time::{Duration, sleep},
};

use crate::tui::{
    command::{self, Command, ThemeCommand},
    keymap::{Intent, Keymap},
    menu,
    theme::{Theme, ThemeKind},
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FocusPane {
    Sidebar,
    Main,
    Command,
}

#[derive(Debug)]
enum AppEvent {
    TaskFinished(String),
}

#[derive(Debug)]
pub struct App {
    should_quit: bool,
    focus: FocusPane,
    command_mode: bool,
    command_input: String,
    status: String,
    show_help: bool,
    theme_kind: ThemeKind,
    keymap: Keymap,
    items: Vec<String>,
    selected_item: usize,
    output_scroll: u16,
    counter: i64,
    busy: bool,
    task_tx: mpsc::UnboundedSender<AppEvent>,
    task_rx: mpsc::UnboundedReceiver<AppEvent>,
}

impl Default for App {
    fn default() -> Self {
        let (task_tx, task_rx) = mpsc::unbounded_channel();
        Self {
            should_quit: false,
            focus: FocusPane::Main,
            command_mode: false,
            command_input: String::new(),
            status: "ready".to_string(),
            show_help: false,
            theme_kind: ThemeKind::Neutral,
            keymap: Keymap::default(),
            items: vec![
                "Overview".to_string(),
                "Jobs".to_string(),
                "Logs".to_string(),
                "Settings".to_string(),
            ],
            selected_item: 0,
            output_scroll: 0,
            counter: 0,
            busy: false,
            task_tx,
            task_rx,
        }
    }
}

impl App {
    pub fn should_quit(&self) -> bool {
        self.should_quit
    }

    pub fn poll_tasks(&mut self) {
        while let Ok(event) = self.task_rx.try_recv() {
            match event {
                AppEvent::TaskFinished(message) => {
                    self.busy = false;
                    self.status = message;
                }
            }
        }
    }

    pub fn handle_key_event(&mut self, key: KeyEvent) {
        if self.command_mode {
            self.handle_command_key(key);
            return;
        }

        if self.show_help && key.code == KeyCode::Esc {
            self.show_help = false;
            self.status = "help closed".to_string();
            return;
        }

        if let Some(intent) = self.keymap.intent_for(key) {
            self.handle_intent(intent);
            return;
        }

        self.handle_local_key(key);
    }

    pub fn handle_mouse_event(&mut self, mouse: MouseEvent) {
        match mouse.kind {
            MouseEventKind::ScrollUp => {
                self.output_scroll = self.output_scroll.saturating_sub(2);
            }
            MouseEventKind::ScrollDown => {
                self.output_scroll = self.output_scroll.saturating_add(2);
            }
            MouseEventKind::Down(_) => {
                if mouse.column < 28 {
                    self.focus = FocusPane::Sidebar;
                    let row = mouse.row.saturating_sub(4) as usize;
                    if row < self.items.len() {
                        self.selected_item = row;
                    }
                } else {
                    self.focus = FocusPane::Main;
                }
            }
            _ => {}
        }
    }

    fn handle_intent(&mut self, intent: Intent) {
        match intent {
            Intent::EnterCommandMode => self.enter_command_mode(),
            Intent::Cancel => self.cancel_transient_state(),
            Intent::Help => {
                self.show_help = true;
                self.status = "help opened".to_string();
            }
            Intent::NextPane => self.next_pane(),
            Intent::PreviousPane => self.previous_pane(),
            Intent::Activate => self.activate(),
            Intent::MoveUp => self.move_selection(-1),
            Intent::MoveDown => self.move_selection(1),
            Intent::MoveLeft => self.focus = FocusPane::Sidebar,
            Intent::MoveRight => self.focus = FocusPane::Main,
            Intent::Search => self.status = "search hook: implement local search".to_string(),
        }
    }

    fn handle_local_key(&mut self, key: KeyEvent) {
        if key.modifiers != KeyModifiers::NONE {
            return;
        }

        match key.code {
            KeyCode::Char('+') => {
                self.counter += 1;
                self.status = "counter incremented".to_string();
            }
            KeyCode::Char('-') => {
                self.counter -= 1;
                self.status = "counter decremented".to_string();
            }
            _ => {}
        }
    }

    fn handle_command_key(&mut self, key: KeyEvent) {
        match key.code {
            KeyCode::Esc => self.cancel_transient_state(),
            KeyCode::Enter => self.submit_command(),
            KeyCode::Backspace => {
                self.command_input.pop();
            }
            KeyCode::Char(character) if text_input_modifiers(key.modifiers) => {
                self.command_input.push(character);
            }
            _ => {}
        }
    }

    fn submit_command(&mut self) {
        let input = self.command_input.clone();
        self.command_mode = false;
        self.command_input.clear();
        self.focus = FocusPane::Main;

        match command::parse(&input) {
            Command::Quit { force: _ } => self.should_quit = true,
            Command::Help => {
                self.show_help = true;
                self.status = "help opened".to_string();
            }
            Command::Theme(theme) => self.set_theme(theme),
            Command::Unknown(command) => self.handle_local_command(&command),
            Command::Empty => self.status = "empty command".to_string(),
        }
    }

    fn handle_local_command(&mut self, command: &str) {
        match command {
            "inc" => {
                self.counter += 1;
                self.status = "counter incremented".to_string();
            }
            "dec" => {
                self.counter -= 1;
                self.status = "counter decremented".to_string();
            }
            "task" | "load" => self.start_background_task(),
            _ => self.status = format!("unknown command: {command}"),
        }
    }

    fn start_background_task(&mut self) {
        if self.busy {
            self.status = "task already running".to_string();
            return;
        }

        self.busy = true;
        self.status = "background task running".to_string();
        let task_tx = self.task_tx.clone();
        tokio::spawn(async move {
            sleep(Duration::from_secs(2)).await;
            let _ = task_tx.send(AppEvent::TaskFinished(
                "background task complete".to_string(),
            ));
        });
    }

    fn set_theme(&mut self, theme: ThemeCommand) {
        self.theme_kind = match theme {
            ThemeCommand::Neutral => ThemeKind::Neutral,
            ThemeCommand::Safe => ThemeKind::Safe,
            ThemeCommand::Danger => ThemeKind::Danger,
        };
        self.status = format!("theme: {}", self.theme().name);
    }

    fn enter_command_mode(&mut self) {
        self.command_mode = true;
        self.command_input.clear();
        self.command_input.push(':');
        self.focus = FocusPane::Command;
        self.status = "command mode".to_string();
    }

    fn cancel_transient_state(&mut self) {
        if self.show_help {
            self.show_help = false;
            self.status = "help closed".to_string();
            return;
        }

        if self.command_mode {
            self.command_mode = false;
            self.command_input.clear();
            self.focus = FocusPane::Main;
            self.status = "command canceled".to_string();
            return;
        }

        self.status = "nothing to cancel".to_string();
    }

    fn next_pane(&mut self) {
        self.focus = match self.focus {
            FocusPane::Sidebar => FocusPane::Main,
            FocusPane::Main => FocusPane::Command,
            FocusPane::Command => FocusPane::Sidebar,
        };
    }

    fn previous_pane(&mut self) {
        self.focus = match self.focus {
            FocusPane::Sidebar => FocusPane::Command,
            FocusPane::Main => FocusPane::Sidebar,
            FocusPane::Command => FocusPane::Main,
        };
    }

    fn activate(&mut self) {
        match self.focus {
            FocusPane::Sidebar => {
                self.status = format!("selected {}", self.items[self.selected_item]);
            }
            FocusPane::Main => {
                self.start_background_task();
            }
            FocusPane::Command => self.enter_command_mode(),
        }
    }

    fn move_selection(&mut self, delta: isize) {
        if self.focus != FocusPane::Sidebar || self.items.is_empty() {
            return;
        }

        let last = self.items.len() - 1;
        self.selected_item = self.selected_item.saturating_add_signed(delta).min(last);
    }

    fn theme(&self) -> Theme {
        self.theme_kind.theme()
    }

    pub fn render(&mut self, frame: &mut Frame<'_>) {
        let theme = self.theme();
        let area = frame.area();
        frame.render_widget(Clear, area);

        let rows = Layout::default()
            .direction(Direction::Vertical)
            .constraints([
                Constraint::Length(3),
                Constraint::Min(8),
                Constraint::Length(4),
            ])
            .split(area);

        self.render_header(frame, rows[0], &theme);

        let body = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([Constraint::Length(28), Constraint::Min(30)])
            .split(rows[1]);

        self.render_sidebar(frame, body[0], &theme);
        self.render_main(frame, body[1], &theme);
        self.render_command(frame, rows[2], &theme);

        if self.show_help {
            self.render_help(frame, centered_rect(area, 72, 70), &theme);
        }
    }

    fn render_header(&self, frame: &mut Frame<'_>, area: Rect, theme: &Theme) {
        let title = Line::from(vec![
            Span::styled(
                " rustui app ",
                Style::default()
                    .fg(theme.background)
                    .bg(theme.accent)
                    .add_modifier(Modifier::BOLD),
            ),
            Span::raw(" "),
            Span::styled(
                theme.name,
                Style::default()
                    .fg(theme.text)
                    .bg(theme.accent_dark)
                    .add_modifier(Modifier::BOLD),
            ),
            Span::raw(format!("  focus: {:?}", self.focus)),
        ]);
        let block = Block::default()
            .borders(Borders::ALL)
            .border_style(Style::default().fg(theme.border))
            .style(Style::default().bg(theme.panel));
        frame.render_widget(Paragraph::new(title).block(block), area);
    }

    fn render_sidebar(&self, frame: &mut Frame<'_>, area: Rect, theme: &Theme) {
        let items: Vec<ListItem<'_>> = self
            .items
            .iter()
            .map(|item| ListItem::new(item.as_str()))
            .collect();
        let mut state = ListState::default();
        state.select(Some(self.selected_item));
        let block = panel_block("Browser", self.focus == FocusPane::Sidebar, theme);
        let list = List::new(items)
            .block(block)
            .highlight_style(
                Style::default()
                    .fg(theme.background)
                    .bg(theme.accent)
                    .add_modifier(Modifier::BOLD),
            )
            .highlight_symbol(">");
        frame.render_stateful_widget(list, area, &mut state);
    }

    fn render_main(&self, frame: &mut Frame<'_>, area: Rect, theme: &Theme) {
        let selected = self.items.get(self.selected_item).map_or("", String::as_str);
        let text = vec![
            Line::from("Empty TUI scaffold"),
            Line::from(""),
            Line::from(format!("Selected: {selected}")),
            Line::from(vec![
                Span::raw("Counter: "),
                Span::styled(self.counter.to_string(), theme.selector("counter.value")),
            ]),
            Line::from(format!(
                "Task: {}",
                if self.busy { "running" } else { "idle" }
            )),
            Line::from(""),
            Line::from("Local adaptation points:"),
            Line::from("  src/app.rs              app state and behavior"),
            Line::from("  src/tui/keymap.rs       common key policy"),
            Line::from("  src/tui/style.rs        design tokens and selectors"),
            Line::from("  src/tui/theme.rs        color roles and themes"),
            Line::from("  src/tui/menu.rs         footer/help menus"),
            Line::from(""),
            Line::from("Try: :theme safe, :theme danger, :inc, :dec, :task, ?"),
            Line::from(vec![
                Span::styled(" + increment ", theme.selector("button.increment")),
                Span::raw(" / "),
                Span::styled(" - decrement ", theme.selector("button.decrement")),
                Span::raw(" selectors are local app style rules."),
            ]),
        ];
        let block = panel_block("Output", self.focus == FocusPane::Main, theme);
        frame.render_widget(
            Paragraph::new(text)
                .block(block)
                .style(Style::default().fg(theme.text).bg(theme.panel))
                .scroll((self.output_scroll, 0))
                .wrap(Wrap { trim: false }),
            area,
        );
    }

    fn render_command(&self, frame: &mut Frame<'_>, area: Rect, theme: &Theme) {
        let prompt = if self.command_mode {
            Line::from(vec![
                Span::styled("cmd ", Style::default().fg(theme.accent)),
                Span::raw(self.command_input.clone()),
            ])
        } else {
            Line::from(vec![
                Span::styled("status ", Style::default().fg(theme.muted)),
                Span::raw(self.status.clone()),
            ])
        };

        let footer = menu::footer(&self.keymap, &theme);
        let block = panel_block("Command", self.focus == FocusPane::Command, theme);
        frame.render_widget(
            Paragraph::new(vec![prompt, footer])
                .block(block)
                .style(Style::default().fg(theme.text).bg(theme.panel)),
            area,
        );
    }

    fn render_help(&self, frame: &mut Frame<'_>, area: Rect, theme: &Theme) {
        frame.render_widget(Clear, area);
        let block = Block::default()
            .title("Help")
            .borders(Borders::ALL)
            .border_style(Style::default().fg(theme.accent))
            .style(Style::default().bg(theme.panel));
        frame.render_widget(
            Paragraph::new(menu::help_lines(&self.keymap, self.theme_kind))
                .block(block)
                .style(Style::default().fg(theme.text).bg(theme.panel))
                .wrap(Wrap { trim: false }),
            area,
        );
    }
}

fn panel_block(title: &'static str, focused: bool, theme: &Theme) -> Block<'static> {
    let border = if focused { theme.accent } else { theme.border };
    Block::default()
        .title(title)
        .borders(Borders::ALL)
        .border_style(Style::default().fg(border))
        .style(Style::default().bg(theme.panel))
}

fn text_input_modifiers(mut modifiers: KeyModifiers) -> bool {
    modifiers.remove(KeyModifiers::SHIFT);
    modifiers.is_empty()
}

fn centered_rect(area: Rect, percent_x: u16, percent_y: u16) -> Rect {
    let vertical = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Percentage((100 - percent_y) / 2),
            Constraint::Percentage(percent_y),
            Constraint::Percentage((100 - percent_y) / 2),
        ])
        .split(area);

    let horizontal = Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage((100 - percent_x) / 2),
            Constraint::Percentage(percent_x),
            Constraint::Percentage((100 - percent_x) / 2),
        ])
        .split(vertical[1]);

    horizontal[1]
}
"#;

#[cfg(test)]
mod tests {
    use super::{is_valid_package_name, package_name_for, project_files};
    use std::path::Path;

    #[test]
    fn validates_package_names() {
        assert!(is_valid_package_name("rdbt"));
        assert!(is_valid_package_name("my-tui"));
        assert!(is_valid_package_name("my_tui"));
        assert!(!is_valid_package_name(""));
        assert!(!is_valid_package_name("1bad"));
        assert!(!is_valid_package_name("bad name"));
    }

    #[test]
    fn derives_package_name_from_target_path() {
        assert_eq!(
            package_name_for(Path::new("/tmp/my-tui")).unwrap(),
            "my-tui"
        );
    }

    #[test]
    fn includes_core_template_files() {
        let files = project_files("demo");
        assert!(files.iter().any(|(path, _)| *path == "Cargo.toml"));
        assert!(files.iter().any(|(path, _)| *path == "src/tui/keymap.rs"));
        assert!(files.iter().any(|(path, _)| *path == "src/tui/style.rs"));
        assert!(files.iter().any(|(path, _)| *path == "src/tui/theme.rs"));
    }

    #[test]
    fn generated_style_template_supports_selectors() {
        let files = project_files("demo");
        let style = files
            .iter()
            .find_map(|(path, contents)| (*path == "src/tui/style.rs").then_some(contents))
            .expect("style template");

        assert!(style.contains("pub struct Design"));
        assert!(style.contains("pub fn selector"));
        assert!(style.contains("pub enum Role"));
    }

    #[test]
    fn generated_template_uses_tokio_backbone() {
        let files = project_files("demo");
        let cargo = files
            .iter()
            .find_map(|(path, contents)| (*path == "Cargo.toml").then_some(contents))
            .expect("cargo template");
        let main = files
            .iter()
            .find_map(|(path, contents)| (*path == "src/main.rs").then_some(contents))
            .expect("main template");
        let tui = files
            .iter()
            .find_map(|(path, contents)| (*path == "src/tui/mod.rs").then_some(contents))
            .expect("tui template");
        let app = files
            .iter()
            .find_map(|(path, contents)| (*path == "src/app.rs").then_some(contents))
            .expect("app template");

        assert!(cargo.contains("tokio"));
        assert!(main.contains("#[tokio::main]"));
        assert!(tui.contains("tokio::select!"));
        assert!(app.contains("pub fn poll_tasks"));
        assert!(app.contains("tokio::spawn"));
    }
}
